### ISSUE TITLE
Horizontal Green Bars on Screen at Retrobat

### ISSUE THREAD

**Issue by TeslaBR** [RetroBat-Official/emulatorlauncher#106]
Hello, i need help with a question.

I started to make my retrosystem to play retrogames (specially PS2). I'm using Retrobat (downloaded and installed from the site)

But as soon as I open it, i got on display horizontal green lines and don't know how to solve it. I tried everything (Run as adm, changed compatibility settings, changed DPI settings like this https://github.com/kaylh/old-RetroBat-obsolete/issues/28 @kaylh @4gordi, reinstalled the dependancies needed for retrobat and emulators (direct3d, visual c++ 2010, 2015,2017,2019), updated video driver, tried to change resolution,  fullscreen and windowed mode, Hz from the monitor (60Hz or 144Hz), tried to run from retrobat.exe and  emulationstation.exe, tried the FAQ option too (changing the scales) but nothing solved. Anyone can help me?

![Sem título](https://github.com/TeslaBR/Horizontal-Green-Bars-on-Screen-at-Retrobat/assets/144844546/8976faa4-e6b9-4a69-96a1-c36199410b21)

My configuration:
ACER Nitro 5
i5 10300h , 32Gb RAM, GTX 1650Ti, 512SSD and 1Tb HD, running on Win 10. It happens at my 2 monitors.

**Comment by lorenzolamas** [comment]
Hi guy,

You've read the **FUCKING** FAQ ?

"RTFFAQ" ;-)

Tips: the fucking FAQ is on the official Retrobat website, just cilc on the FAQ menu...

**Comment by TeslaBR** [comment]
That's the first time that i've opened a github. I don't know if it's correct.

But yes, I tried the FAQ solution, do not work. https://retrobat.forumgaming.fr/t135p35-faq-retrobat-wip#4625

**Comment by lorenzolamas** [comment]
You weren't talking about this solution in your post...
This solution has existed for over a year and before you, ALL users have solved this problem with this solution.
For now, There is no other solution than to put the scale at 100%.
For your next questions, Retrobat support is on the forum (where there is the FAQ) and on our Discord.

**Comment by TeslaBR** [comment]
That's another solution that worked for me month's ago, but now now.

At official discord I got help, and fixed with it https://www.windowscentral.com/how-force-your-surface-book-use-its-dedicated-gpu-games

I was getting without ideas, and it worked.
