### ISSUE TITLE
Add Flycast if possible

### ISSUE THREAD

**Issue by Edu789** [RetroBat-Official/emulatorlauncher#11]
This emulator is compatible in addition to the Dreamcast with the arcade boards Naomi 1, 2 and Atomiswave...

**Comment by Tartifless** [comment]
https://github.com/RetroBat-Official/emulatorlauncher/commit/44dd417bc6505db62eb6f57f6d6d2f0273ff1fb3

**Comment by Tartifless** [comment]
Already added
