### ISSUE TITLE
Some EmulationStation settings are ignored by RetroArch

### ISSUE THREAD

**Issue by joerg-knitter** [RetroBat-Official/emulatorlauncher#317]
Testing RetroBat 5.3 for a while (while also being a Batocera user on other non-Windows hardware) I saw some options in EmulationStation that are apparently ignored by RetroArch. Unfortunately, I don´t have a full list of what is working and what is not, but I can give some examples:
- When I select "Game settings/Per system advanced configuration/dos/emulation/load dosbox.conf -> dosbox.conf (in zip or folder)", the dosbox pure menu is shown nevertheless and the dosbox.conf is being ignored.
- "Game settings/Per system advanced settings/Commodore 64/visual rendering/crop" is being ignored - RetroArch currently is set to "small" for this core. Maybe, I changed this setting after having set "Game settings/user interface/show menu elements" to "full" and configured and saved the setting within RetroArch itself... - can´t remember exactly...
- Setting "Game settings/user interface/notifications" to "on" does not show the RetroArch notification settings - at least I would expect to see a notification when enabling or disabling the keyboard focus with the "scroll" key (as I am used to when using RetroArch normally).

If I understood right, the emulators are started with the help of the emulatorlauncher.exe in the emulationstation directory, where also the log is located. 
This log tells me that e.g. the DOS game "Stunts" is started with 'D:\RetroBat\emulators\retroarch\retroarch.exe -L "D:\RetroBat\emulators\retroarch\cores\dosbox_pure_libretro.dll" "D:\RetroBat\roms\dos\Stunts.zip" --set-shader "D:\RetroBat\emulators\retroarch\shaders\shaders_slang\crt\fakelottes_mod.slangp'. I don´t see any additional config parameter here.

My es_settings.cfg says:
`<string name="dos.core" value="dosbox_pure" />`
`<string name="dos.dosbox_pure_conf" value="early_auto" />`
`<string name="dos.emulator" value="libretro" />`

It has been updated today, so my changes are in fact saved there.

But the config files in D:\RetroBat\emulators\retroarch\config\DOSBox-pure are from 2023 and just contain custom viewport and a few controller settings. So if they are used as default settings, they do not contain the changes of the es_settings.cfg.

The same is with the Vice settings - launch command from the log: 'D:\RetroBat\emulators\retroarch\retroarch.exe -L "D:\RetroBat\emulators\retroarch\cores\vice_x64sc_libretro.dll" "D:\RetroBat\roms\c64\Turrican.zip" --set-shader "D:\RetroBat\emulators\retroarch\shaders\shaders_slang\crt\fakelottes_mod.slangp'

es_settings.cfg:
`<string name="c64.core" value="vice_x64sc" />`
`<string name="c64.emulator" value="libretro" />`
`<string name="c64.vice_crop" value="disabled" />`
`<string name="c64.vice_crop_mode" value="both" />`

Is there anything I have mis-understood regarding the configuration and/or inner workings of RetroBat? Anything wrong in my configuration? Or was it a know problem that has already been fixed with v6.0 (beta)? Haven´t seen an issue dealing with this...

Thanks a lot in advance for your support!

**Comment by Tartifless** [comment]
Hello,
The retroarch settings are applied in retroarch.cfg file.
The core options are applied to retroarch_core_options.cfg

We do not use per core configuration file.

Regarding DOSBOX, if i remember well we have fixed the issue in v6 that is coming soon, so now the value correctly affects the core setting "dosbox_pure_conf" with one of the following values: 
- false
- inside
- outside

Regarding commodore 64 (vicex64), this affects the core option "vice_crop", and can set the following values:
- disabled
- small
- medium
- maximum
- auto_disable
- auto

Finally, the notifications option affects retroarch.cfg option "video_font_enable" with the values "true" or "false"

**Comment by Tartifless** [comment]
From what i can see, all these options are ok and are working

**Comment by joerg-knitter** [comment]
I might have found the reasons for 2 of the mentioned problems:
- Regarding the vicex64sc zoom modes, the right core option is "vice_zoom_mode", not "vice_crop"
- To make the notification show correctly (i.e. also during emulation, not just when entering the RetroArch menu), "input_overlay_behind_menu" must be set to "true" (it seems to be "false" by default).

**Comment by joerg-knitter** [comment]
"vice_crop" and "vice_crop_mode" are the wrong key names, it must say "vice_zoom_mode" and "vice_zoom_mode_crop".

And enabling notifications in "Game Settings/User Interface/Notification" feels kind of pointless as long as they are not visible by setting "input_overlay_behind_menu" to "true".

So I would regards both being bugs, not feature requests.

**Comment by Tartifless** [comment]
No, the options zoom and zoom crop are deprecated in vice for a long time now ==> you need to update your core file.

What notifications are not visible, i have all notifications correctly displaying !

**Comment by joerg-knitter** [comment]
First of all: Thanks a lot for your patience - and your explanation above regarding the inner workings of the RetroBat config management!

I reinstalled RetroBat to another drive, and in fact, the C64 problems seemed to be gone. Then I compared the settings of both installations and recognized that I changed the default core for C64 in my first setup from "vice x64" to "vice x64sc". Apparently, "vice x64sc" is more compatible, and "vice x64" has been deprecated in the standalone vice emulator for years. Using the "vice x64" core, the crop settings indeed work, using "vice x64sc" instead, they are ignored.

Regarding the notifications, you are right, it works on the new setup, but it also finally worked on the old one without the mentioned config changes above - sorry for the confusion and especially not being able to reproduce anymore why it did not work beforehand. I also had d3d12 enabled instead of your default gl, but this did not seem to be the root cause of the problem when I retestet it. So you can also remove the notification topic from the list.

**Comment by Tartifless** [comment]
Hello,

The setting is the same with vice x64sc, you should also update vice x64sc, because it affects the same lines is retroarch config file with latest versions.

**Comment by joerg-knitter** [comment]
The reinstall was also a clean 5.3 install, and there was no core update available. If 6.x solves the problem, you can indeed close the ticket.

**Comment by Tartifless** [comment]
You could also update the vicex64 and vicex64sc cores from within retroarch, so the features will work
