### ISSUE TITLE
[ Bug ] View Customizations File Extensions

### ISSUE THREAD

**Issue by FiveOver14** [RetroBat-Official/emulatorlauncher#351]
Good morning, Good Afternoon and Good Night,

Found an annoying little bug in the 'View Customization - File Extensions'

Here's what happens.

Was working under the NES system. Choose to hide some of the file extensions so I could only see those games with those file extensions. There are five options those being
.7z
.fds
.nes
.wad
.zip

I only wanted to see those files with the .zip extension. Unfortunately, there was none with that '.zip' extension. Therefore, Retrobat crashed and once restarted, the NES Console was no longer showing under the available consoles.

And with no way of seeing the console, we could not go back into the View Customization -> File Extensions and recheck to see the other extensions.

To get the console back, we had to open the 'es_settings.cfg' file and remove the <string name="nes.HiddenExt" value="**************" /> and save the file.

Once that was done, the console came back and all was back to normal.

Therefore, I do believe that there should be a way to still see the console, but have no games displayed so that one can re-initialize those extensions.

FiveOver

PS, Also posted over at the following url:  https://retrobat.forumgaming.fr/t1984-bug-view-customizations-file-extensions

**Comment by FiveOver14** [comment]
Under this section: To get the console back, we had to open the 'es_settings.cfg' file and remove the and save the file.

The full sentence should of been : To get the console back, we had to open the 'es_settings.cfg' file and remove the < string name="nes.HiddenExt" value="**************" / > and save the file.

**Comment by Tartifless** [comment]
Hello, 

Not a bug, you just have to enable this option: SHOW EMPTY SYSTEMS
![image](https://github.com/RetroBat-Official/emulatorlauncher/assets/13442986/8e949582-4bd5-45e8-a991-b2e61b0a9fea)

Then you can go in the system and re-enable all extensions.
