### ISSUE TITLE
vpinball not launching b2s

### ISSUE THREAD

**Issue by estivalet** [RetroBat-Official/emulatorlauncher#353]
Hey, just updated to retrobat 6.0 and noticed the same problem some guys are having in this thread https://retrobat.forumgaming.fr/t1997-vpinballx-not-launching-b2s with my pinball tables. Tested by command line and you guys only need to pass-ExtMinimized not -Minimized

The .ini is not required at all from emulatorlauncher point of you, it's only good on a per table use case. Visual Pinball is smart enough to pickup on .ini and .directb2s on it's own, there is no need to have emulatorlauncher invoke extra -ini parameters, try it in your end to confirm that.

Please stick to this command line all will be good. V:\RetroBat\emulators\vpinball\VPinballX.exe -ExtMinimized -play "V:\RetroBat\roms\vpinball\RETRO-BLISS Pinball.vpx"

I'm also adding this as an issue in the github.

Thanks!

**Comment by fabricecaruso** [comment]
The official supported vpinball version is 10.7.4.0.
You probably just use an unsupported version ( and don't tell us )
Is it 10.7.4.0 version ?

**Comment by estivalet** [comment]
forget to mention that I'm using vpinball 10.8 RC1

**Comment by fabricecaruso** [comment]
Well... 
If you modify your installation yourself, and when it's not the official supported versions, it's at your own risk.

After some research, It's not related AT ALL to the -Ini commandline which will stay in place.
In the meanwhile, delete you whole vpinball folder then reinstall with the default x86 version 10.7.4.0 we provide.
