### ISSUE TITLE
Cemu with a/b x/y switch is not working

### ISSUE THREAD

**Issue by thestift** [RetroBat-Official/emulatorlauncher#370]
Hi!
It seems the switch for A/B x/y for Cemu is at least for me not working..
Is perhaps the reason in the generation where
 Program.SystemConfig.isOptSet("gamepadbuttons")  -- from [emulatorLauncher/Generators/Cemu.Controllers.cs]
is used instead of "cemu_ gamepadbuttons" or what the correct value is?
Thanks for the great app!

**Comment by Tartifless** [comment]
By the way : this feature only works if you have a XInput controller, what controller do you have and why would you need to revert buttons ? 
For information the standard / default layout is based on the buttons positions of the original console.
So pressing the button positionned "SOUTH" will do the action that the "SOUTH" button was doing on the original wiiU.

**Comment by Tartifless** [comment]
#371

**Comment by thestift** [comment]
It could be case  that this is the problem its a stadia controller and when the controller manually setup it uses only SDL and not Xinput.
`<mappings>
			<entry>
				<mapping>1</mapping>
				<button>1</button>
			</entry>
			<entry>
				<mapping>2</mapping>
				<button>0</button>
			</entry>
			<entry>
				<mapping>3</mapping>
				<button>3</button>
			</entry>
`
Yeah you are right this is the reason because its not XInput.
The button orientation is clear but I want to press the characters which are displayed in the game(i ignore here psx games). And the configuration of the orientation is global or? or is it per system?
Thanks for the change you have done to enable also this for SDL controllers - is there perhaps a nightly run?

**Comment by Tartifless** [comment]
The parameter is for the system (wiiu), not global.
The option exists for multiple systems however, you'll have to enable it in each of these.

**Comment by Tartifless** [comment]
> is there perhaps a nightly run?

Yes there is here:
https://github.com/RetroBat-Official/emulatorlauncher/releases/download/continuous/batocera-ports.zip

just extract this in your retrobat\emulationstation folder

**Comment by thestift** [comment]
I only replaced the emulatorLauncher.exe
thanks a lot now its working 👍
