### ISSUE TITLE
vita3k.Generator.cs not using pref-path

### ISSUE THREAD

**Issue by jsesp82** [RetroBat-Official/emulatorlauncher#402]
Hi,

I have set up a drive for my installed games using pref-path that is not the same as the vita3k emulator. I believe vita3k.Generator.cs is assuming that games are in the same path as the emulator and does not take pref-path into account, so it does not work for me.

            string path = AppConfig.GetFullPath("vita3k");
            ...
           //check if game is already installed or not (if installed game folder with gameID name exists in ux0\app\<gameID> folder)
            //if game is not yet installed ==> install it
            //if game is installed ==> run it
            string gamepath = Path.Combine(path, "ux0", "app", gameID);

In addition, when disableautoconfig is false, it always overwrites pref-path with the path of the emulator.

           //write pref-path with emulator path
            string vita_emulator_path = AppConfig.GetFullPath("vita3k");
            yml["pref-path"] = vita_emulator_path;

It would be great if pref-path can be included in the logic to allow this configuration to work.

Thank you very much.

**Comment by jsesp82** [comment]
I believe there is also a "." missing in this command on line 74. It should be ".m3u", which may be enough to make it work with pref-path.

if (Directory.Exists(gamepath) || ext == "m3u")

Thanks

**Comment by Tartifless** [comment]
Hello,
#405 
RetroBat will use existing pref-path from config.yml if set, else will default to emulator folder.
