### ISSUE TITLE
search for [#GameID] in file name for vita3k.Generator.cs .m3u files if they are empty

### ISSUE THREAD

**Issue by jsesp82** [RetroBat-Official/emulatorlauncher#404]
For large collections, it is easier to generate the .m3u file names copying the .zip that contain the [#gameID] than to include the game ID in all the .m3u files.

**Comment by Tartifless** [comment]
Hello,

Vita3K accepts .m3u .psvita .vpk extensions, if you use .psvita or .vpk you can just put the game ID between [ ] and RetroBat will use this.

**Comment by jsesp82** [comment]
Thank you. I thought only .m3u should be used if the files are installed. .psvita and .vpk files would try to be installed.

            if (!Directory.Exists(gamepath) && (ext == ".vpk" || ext == ".psvita"))
                commandArray.Add("-path " + "\"" + rom + "\"");     //path used to install the game

            if (Directory.Exists(gamepath) || ext == ".m3u")
                commandArray.Add("-r " + gameID);                    //r used to run installed games
