### ISSUE TITLE
Misconfiguration of RetroArch using SwanStation and PAL games

### ISSUE THREAD

**Issue by silverlays** [RetroBat-Official/emulatorlauncher#447]
Hi 👋 

For starters, I hope I'm in the right place 😳 

I'm a French user and started using RetroBat fairly recently. During my configuration phase, I noticed something strange, and I don't understand how to override it.

Already, almost everything is left by default in RetroBat then, When I want to launch a PAL game with aspect ratio on AUTO, the image is good in height, but not in width. After a bit of research, I found the problem: the **swanstation_Display_AspectRatio** line is set to Auto, and therefore to **corrected (NTFS)**. When i switch this settings to **corrected (Native)**, everything back to normal, until I leave RetroArch of course.

After this context, my question is simple: Would it be possible to add **Native** in the advanced video options for lr_swanstation please?

In the meantime, I've tried several methods to modify this value myself in ALL the **retroarch-core-options.cfg** files I could find, as well as in the configgen JSON, but to no avail 😢  If you have a temporary/definitive method, I'm really interested.

Thanks in advance

**Comment by Tartifless** [comment]
Hello, will be fixed in 6.2

**Comment by Tartifless** [comment]
https://github.com/RetroBat-Official/emulatorlauncher/commit/643ba1000105f5b2cbda6b857aa3dbb15ae61770

**Comment by silverlays** [comment]
Thanks a lot 🙏
