### ISSUE TITLE
add .squashfs for  3ds emulator

### ISSUE THREAD

**Issue by aderumier** [RetroBat-Official/emulatorlauncher#532]
Hi,

Batocera have added support for .squahfs format to 3ds 

https://github.com/batocera-linux/batocera.linux/pull/12005

I could be great to have support for retrobat too to have compatible romset between both systems.
(I have done the original patch for batocera, but I don't known the retrobat code enough to do the patch myself)

**Comment by Tartifless** [comment]
Hello,
I guess the request is for standalone emulators, not for libretro, right ?

**Comment by aderumier** [comment]
Currently with citra standalone indeed.  (tested with old citra, and new  citra PabloMK7 fork) 

(but I think it should work with libretro , at least on batocera, the .squashfs is simply mounted live, and the .3ds file is passed as argument to the emulator command-line)
