### ISSUE TITLE
Dolphin Network/Netplay Menu integration

### ISSUE THREAD

**Issue by Sabinremson** [RetroBat-Official/emulatorlauncher#557]
Dolphin Network/Netplay Menu integration

Implement the ability to specify the region as custom and the ip address, as well as additional netplay options that currently exist in the Dolphin Emulation .

**Comment by Tartifless** [comment]
Hello,
Unfortunately, Dolphin requires to go to the emulator interface to start or join a netplay session, there is no way around this, so it won't be possible to integrate this one in RetroBat in an automated way.
