### ISSUE TITLE
Addition of 7z option

### ISSUE THREAD

**Issue by ghost911-hub** [RetroBat-Official/emulatorlauncher#603]
Hello already thank you for your great work on retrobat I would like to make a request for the ps2 games would it be possible to add a 7z decompression to the ps2 roms in a temporary folder of our choice example: a z:\ ramdisk or an ssd because the 7z format allows me to save 50% space on my hard drive compared to a gz this optional function would be a big advantage extracting it before launching it with the emulator

![349046229-0c2109a2-b8c9-42e0-918e-59e28454e30f](https://github.com/user-attachments/assets/51a253e7-e835-482f-800f-441518ea3e5f)
![349046232-9c716d8b-7fc6-4bb8-9869-f4674a88fb42](https://github.com/user-attachments/assets/b17f7f36-aa90-4a7d-a1ee-8ada77d3bdd1)
![349046224-a88ca0f0-a768-4801-9c3f-22fda600e835](https://github.com/user-attachments/assets/37b18247-1edd-4b84-9b4f-f7f5057b5f4f)

a bit like launchbox and its extension to give you an idea: https://github.com/fraganator/archive-cache-manager

**Comment by Tartifless** [comment]
Hello,
For ps2 it's better to use .chd, the approach from launchbox is not the best one.

**Comment by ghost911-hub** [comment]
Hello chd is not equivalent to 7z in terms of compression rate I have not found a better solution than 7z in any case launchbox responds to a space problem on hard drives especially when there are a lot of games in 7z decompression options in a directory of our choice there is still a saving of 50% space compared to chd or gz
