### ISSUE TITLE
[Error] La clé donnée était absente du dictionnaire.

### ISSUE THREAD

**Issue by FRANCKYNO** [RetroBat-Official/emulatorlauncher#641]
Depuis la version 6.3.1, j'ai une erreur "La clé donnée était absente du dictionnaire" au lancement d'un jeu sous RetroArch. Voici le log emulatorLauncher.
En remplaçant le fichier emulatorLauncher.exe par son ancienne version 6.3.0 du 17/07/2024, je n'ai plus d'erreur et le jeu se lance correctement. Je pense qu'il y a un problème avec la dernière version d'emulatorLauncher.exe.

![Capture d'écran 2024-09-20 184936](https://github.com/user-attachments/assets/edef4757-3e52-48d7-95d9-a88ee7a6dc30)
![Capture d'écran 2024-09-20 185219](https://github.com/user-attachments/assets/731222a1-e9be-451b-bdc6-27419ed49e9a)

**Comment by Tartifless** [comment]
Tu peux partager ton es_input, j'ai l'impression qu'un bouton indispensable manque sur ta manette

**Comment by FRANCKYNO** [comment]
Le voici 

<?xml version="1.0"?>
<inputList>
	<inputConfig type="keyboard" deviceName="Keyboard" deviceGUID="-1">
		<input name="a" type="key" id="120" value="1" />
		<input name="b" type="key" id="122" value="1" />
		<input name="down" type="key" id="1073741905" value="1" />
		<input name="hotkey" type="key" id="1073742052" value="1" />
		<input name="l2" type="key" id="1073741898" value="1" />
		<input name="l3" type="key" id="1073741897" value="1" />
		<input name="left" type="key" id="1073741904" value="1" />
		<input name="pagedown" type="key" id="1073741902" value="1" />
		<input name="pageup" type="key" id="1073741899" value="1" />
		<input name="r2" type="key" id="1073741901" value="1" />
		<input name="r3" type="key" id="127" value="1" />
		<input name="right" type="key" id="1073741903" value="1" />
		<input name="select" type="key" id="8" value="1" />
		<input name="start" type="key" id="13" value="1" />
		<input name="up" type="key" id="1073741906" value="1" />
		<input name="x" type="key" id="113" value="1" />
		<input name="y" type="key" id="115" value="1" />
	</inputConfig>
	<inputConfig type="joystick" deviceName="Xbox 360 Controller" deviceGUID="030000005e0400008e02000000007200">
		<input name="a" type="button" id="0" value="1" />
		<input name="b" type="button" id="1" value="1" />
		<input name="down" type="hat" id="0" value="4" />
		<input name="hotkey" type="button" id="6" value="1" />
		<input name="joystick1left" type="axis" id="0" value="-1" />
		<input name="joystick1up" type="axis" id="1" value="-1" />
		<input name="joystick2left" type="axis" id="2" value="-1" />
		<input name="joystick2up" type="axis" id="3" value="-1" />
		<input name="l2" type="axis" id="4" value="1" />
		<input name="l3" type="button" id="8" value="1" />
		<input name="left" type="hat" id="0" value="8" />
		<input name="pagedown" type="button" id="5" value="1" />
		<input name="pageup" type="button" id="4" value="1" />
		<input name="r2" type="axis" id="5" value="1" />
		<input name="r3" type="button" id="9" value="1" />
		<input name="right" type="hat" id="0" value="2" />
		<input name="select" type="button" id="6" value="1" />
		<input name="start" type="button" id="7" value="1" />
		<input name="up" type="hat" id="0" value="1" />
		<input name="x" type="button" id="3" value="1" />
		<input name="y" type="button" id="2" value="1" />
	</inputConfig>
	<inputConfig type="joystick" deviceName="Astro city mini Arcade stick" deviceGUID="03000000a30c00002800000000000000">
		<input name="a" type="button" id="2" value="1" />
		<input name="b" type="button" id="1" value="1" />
		<input name="down" type="axis" id="4" value="1" />
		<input name="hotkey" type="button" id="8" value="1" />
		<input name="left" type="axis" id="0" value="-1" />
		<input name="pagedown" type="button" id="5" value="1" />
		<input name="pageup" type="button" id="4" value="1" />
		<input name="right" type="axis" id="0" value="1" />
		<input name="select" type="button" id="8" value="1" />
		<input name="start" type="button" id="9" value="1" />
		<input name="up" type="axis" id="4" value="-1" />
		<input name="x" type="button" id="0" value="1" />
		<input name="y" type="button" id="3" value="1" />
	</inputConfig>
</inputList>

**Comment by FRANCKYNO** [comment]
Le voici :

<?xml version="1.0"?>
<inputList>
	<inputConfig type="keyboard" deviceName="Keyboard" deviceGUID="-1">
		<input name="a" type="key" id="120" value="1" />
		<input name="b" type="key" id="122" value="1" />
		<input name="down" type="key" id="1073741905" value="1" />
		<input name="hotkey" type="key" id="1073742052" value="1" />
		<input name="l2" type="key" id="1073741898" value="1" />
		<input name="l3" type="key" id="1073741897" value="1" />
		<input name="left" type="key" id="1073741904" value="1" />
		<input name="pagedown" type="key" id="1073741902" value="1" />
		<input name="pageup" type="key" id="1073741899" value="1" />
		<input name="r2" type="key" id="1073741901" value="1" />
		<input name="r3" type="key" id="127" value="1" />
		<input name="right" type="key" id="1073741903" value="1" />
		<input name="select" type="key" id="8" value="1" />
		<input name="start" type="key" id="13" value="1" />
		<input name="up" type="key" id="1073741906" value="1" />
		<input name="x" type="key" id="113" value="1" />
		<input name="y" type="key" id="115" value="1" />
	</inputConfig>
	<inputConfig type="joystick" deviceName="Xbox 360 Controller" deviceGUID="030000005e0400008e02000000007200">
		<input name="a" type="button" id="0" value="1" />
		<input name="b" type="button" id="1" value="1" />
		<input name="down" type="hat" id="0" value="4" />
		<input name="hotkey" type="button" id="6" value="1" />
		<input name="joystick1left" type="axis" id="0" value="-1" />
		<input name="joystick1up" type="axis" id="1" value="-1" />
		<input name="joystick2left" type="axis" id="2" value="-1" />
		<input name="joystick2up" type="axis" id="3" value="-1" />
		<input name="l2" type="axis" id="4" value="1" />
		<input name="l3" type="button" id="8" value="1" />
		<input name="left" type="hat" id="0" value="8" />
		<input name="pagedown" type="button" id="5" value="1" />
		<input name="pageup" type="button" id="4" value="1" />
		<input name="r2" type="axis" id="5" value="1" />
		<input name="r3" type="button" id="9" value="1" />
		<input name="right" type="hat" id="0" value="2" />
		<input name="select" type="button" id="6" value="1" />
		<input name="start" type="button" id="7" value="1" />
		<input name="up" type="hat" id="0" value="1" />
		<input name="x" type="button" id="3" value="1" />
		<input name="y" type="button" id="2" value="1" />
	</inputConfig>
	<inputConfig type="joystick" deviceName="Astro city mini Arcade stick" deviceGUID="03000000a30c00002800000000000000">
		<input name="a" type="button" id="2" value="1" />
		<input name="b" type="button" id="1" value="1" />
		<input name="down" type="axis" id="4" value="1" />
		<input name="hotkey" type="button" id="8" value="1" />
		<input name="left" type="axis" id="0" value="-1" />
		<input name="pagedown" type="button" id="5" value="1" />
		<input name="pageup" type="button" id="4" value="1" />
		<input name="right" type="axis" id="0" value="1" />
		<input name="select" type="button" id="8" value="1" />
		<input name="start" type="button" id="9" value="1" />
		<input name="up" type="axis" id="4" value="-1" />
		<input name="x" type="button" id="0" value="1" />
		<input name="y" type="button" id="3" value="1" />
	</inputConfig>
</inputList>

**Comment by FRANCKYNO** [comment]
Le voici
[es_input..txt](https://github.com/user-attachments/files/17078467/es_input.txt)

Pour ton info, j'ai un stick Sega Astro City mini

**Comment by FRANCKYNO** [comment]
J'ai aussi une erreur bizarre au lancement d'un jeu Switch, Ryujinx m'affiche ce message alors qu'avec l'ancienne version d'emulatorlauncher, aucun problème...
![Capture d'écran 2024-09-20 191445](https://github.com/user-attachments/assets/67335597-f35e-45df-b0f0-7763c25ec876)

**Comment by Tartifless** [comment]
Ça c'est normal, il faut que tu déplaces le dossier portable de ryujinx dans saves\switch\ryujinx
C'est dans le changelog

**Comment by Tartifless** [comment]
Pour retroarch fbneo, tu as mis le driver manette à dinput ?

**Comment by FRANCKYNO** [comment]
Oui, j'ai mis le driver Dinput sur les manettes dans retroarch. j'ai toujours le message "La clé donnée était absente du dictionnaire". D'où ca peut venir ?

**Comment by Tartifless** [comment]
En dinput retrobat utilise le fichier gamecontrollerdb qui est dans system\tools, je pense que ta manette n'y es pas recensée 

Que se passe-t-il avec le pilote sdl2 ?

**Comment by Tartifless** [comment]
Ok ça va être facile à corriger !
Tu peux lancer retroarch, configurer ton contrôleur comme il faut, puis m'envoyer ton fichier retroarch.cfg (après avoir quitté retroarch) ?
Tu sais faire ?

**Comment by Tartifless** [comment]
Et en sdl2 tu n'as pas le message, si ?

Oui-oui la cause est trouvée, c'est facile à résoudre

**Comment by FRANCKYNO** [comment]
J'ai aussi le message en sdl2. Tu as changé quelque chose depuis la dernière version ? La résolution nécessite de corriger le code ?

**Comment by Tartifless** [comment]
Prends le fichier ci-dessous et place-le dans le dossier retrobat\system\tools (tu écrases l'existant).
[gamecontrollerdb.txt](https://github.com/user-attachments/files/17080098/gamecontrollerdb.txt)

**Comment by Tartifless** [comment]
Mais non rien n'a changé depuis la 6.3

**Comment by FRANCKYNO** [comment]
Ca marche maintenant ! le message a disparu.
Tu es trop fort !!!
Je veux bien une petite explication : tu as rajouté quelque chose dans le gamecontrollerdb.txt ?

**Comment by Tartifless** [comment]
Regarde la ligne 20 du fichier, c'est la première ligne en-dessous de RetroBat modified.

Avant il manquait les 4 valeurs dpad (dpup, dpdown, dpleft et dpright), je les ai rajoutées.

Contrôle quand même, par exemple sur un jeu snes, que les boutons et le dpad fonctionnent bien.

**Comment by Tartifless** [comment]
Mais là normalement j'ai également fixé le code, si il ne trouve pas là il va chercher dans es_input...

Par contre, bizarrement, dans es_input tu as pas les mêmes ids pour les axes, tu as 4 pour l'axe vertical, donc bizarre...

**Comment by FRANCKYNO** [comment]
J'ai testé tous les systèmes, tout marche très bien. Je n'ai plus le message "La clé donnée était absente du dictionnaire" .
Un grand merci pour ton aide, 

C'est bien que tu ais rajouté le fait d'aller chercher dans es_input si le gamecontrollerdb est incomplet, cela évitera les futurs problèmes.
